name: BE Pytest

on:
  pull_request:
    branches: ["main", "dev", "feat/SANTAANA-v1.0"]
  push:
    branches: ["dev", "feat/SANTAANA-v1.0"]

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      DJANGO_SETTINGS_MODULE: backend.settings_test
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: .

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest
