name: Cypress Tests Frontend

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install deps
        run: yarn install

      - name: Run Cypress Dev
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096
        run: yarn test:cypress:ci

      - name: Upload screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload videos on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore